name: Metrics

on:
  workflow_dispatch:
  schedule:
   - cron: "0 0 * * *"
  push:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
